### ISSUE TITLE
client is not defined - Error

### ISSUE THREAD

**Issue by oscardobsonbrown** [SM-Wistful/Discord-RoleReact#2]
Hey, I am getting this issue after following you short guide
```/home/pi/.discord/rolereact.js:8
client.on('message', message => {
^

ReferenceError: client is not defined
    at Object.<anonymous> (/home/pi/.discord/rolereact.js:8:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by WalkingDude02** [comment]
did you change the const bot = new Discord.Client(); to const client = new Discord.Client(); ?

**Comment by InternetOscar** [comment]
All g, yeah that was the problem i fixed it a while ago. Soz i didn't report back.
